[window]
padding = { x = 35, y = 35 }

[font]
size = 12.0

[colors.primary]
foreground = '#ada37a'
background = '#000000'

[colors.cursor]
cursor = '#91805a'

[colors.selection]
background = '#172539'
foreground = '#181c27'

[colors.normal]
black   = '#181818'  # color0
red     = '#800009'  # color1
green   = '#48513b'  # color2
yellow  = '#cc8a3e'  # color3
blue    = '#566d8c'  # color4
magenta = '#724c7c'  # color5
cyan    = '#5b4f4a'  # color6
white   = '#ada37e'  # color7


